blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/expo/expo/discussions
    about: For general Expo/React Native questions, please use a discussion forum.
